### ISSUE TITLE
Day-5

### ISSUE THREAD

**Issue by jovicam94** [jovicadev94/airvironment-frontend-summer#23]

**Comment by jovicam94** [comment]
- [x] Add custom APIs #24

- [x] Add Redux support #26

- [x] Display data on Averages page #28
